BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "AGENDA" (
	"id"	INTEGER UNIQUE,
	"Day"	INTEGER,
	"Begin"	INTEGER,
	"End"	INTEGER,
	"Type"	INTEGER,
	"Title"	TEXT,
	FOREIGN KEY("Day") REFERENCES "DAYS"("id_day"),
	FOREIGN KEY("Type") REFERENCES "Type"("id_type"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "AGENDA_TYPE" (
	"id"	INTEGER UNIQUE,
	"Day"	INTEGER,
	"Begin"	INTEGER,
	"End"	INTEGER,
	"Type"	INTEGER,
	"Title"	TEXT,
	FOREIGN KEY("Day") REFERENCES "DAYS"("id_day"),
	FOREIGN KEY("Type") REFERENCES "Type"("id_type"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TYPE" (
	"id_type"	INTEGER UNIQUE,
	"Name"	TEXT,
	PRIMARY KEY("id_type" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "DAYS" (
	"id_day"	INTEGER UNIQUE,
	"Name"	TEXT,
	PRIMARY KEY("id_day" AUTOINCREMENT)
);
INSERT INTO "TYPE" VALUES (0,'Pro');
INSERT INTO "TYPE" VALUES (1,'Perso');
INSERT INTO "TYPE" VALUES (2,'Non défini');
INSERT INTO "DAYS" VALUES (0,'Monday');
INSERT INTO "DAYS" VALUES (1,'Tuesday');
INSERT INTO "DAYS" VALUES (2,'Wednesday');
INSERT INTO "DAYS" VALUES (3,'Thursday');
INSERT INTO "DAYS" VALUES (4,'Friday');
INSERT INTO "DAYS" VALUES (5,'Saturday');
INSERT INTO "DAYS" VALUES (6,'Sunday');

INSERT INTO "AGENDA" VALUES (1,0,600,660,0,'Réunion');
INSERT INTO "AGENDA" VALUES (2,0,600,720,0,'Réunion');
INSERT INTO "AGENDA" VALUES (3,0,660,720,0,'Réunion');
INSERT INTO "AGENDA" VALUES (4,0,1200,1260,0,'Réunion');
INSERT INTO "AGENDA" VALUES (5,4,1200,1260,0,'Réunion');
INSERT INTO "AGENDA" VALUES (6,4,660,720,0,'Réunion');
COMMIT;
